export type IntentType =
  | "STAFF_SUPERVISION_REMINDER"
  | "STAFF_CLOSING_PROCEDURE_STEP"
  | "STAFF_PARTY_ROOM_TURNOVER"
  | "CUSTOMER_PLAYAREA_CAPACITY_NOTICE"
  | "CUSTOMER_CLOSING_SOON"
  | "CUSTOMER_GENERIC_INFO";
